server:
  context-path: /api/voting
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ruling-voting-db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

axon:
  amqp:
    exchange: ruling-voting.events

